//导出所有action
export default {
    THEME_CHANGE: "THEME_CHANGE",
    THEME_INIT: "THEME_INIT",
    SHOW_THEME_VIEW:"SHOW_THEME_VIEW",
    POPULAR_REFRESH: "POPULAR_REFRESH",
    POPULAR_REFRESH_FAIL: "POPULAR_REFRESH_FAIL",
    POPULAR_REFRESH_SUCCESS: "POPULAR_REFRESH_SUCCESS",
    POPULAR_LOAD_MORE_SUCCESS: "POPULAR_LOAD_MORE_SUCCESS",
    POPULAR_LOAD_MORE_FAIL: "POPULAR_LOAD_MORE_FAIL",
    //趋势模块
    TRENDING_REFRESH: 'TRENDING_REFRESH',
    TRENDING_REFRESH_FAIL: 'TRENDING_REFRESH_FAIL',
    TRENDING_REFRESH_SUCCESS: 'TRENDING_REFRESH_SUCCESS',
    TRENDING_LOAD_MORE_SUCCESS: 'TRENDING_LOAD_MORE_SUCCESS',
    TRENDING_LOAD_MORE_FAIL: 'TRENDING_LOAD_MORE_FAIL',
    //收藏模块
    FAVORITE_LOAD_DATA:'FAVORITE_LOAD_DATA',
    FAVORITE_LOAD_SUCCESS:'FAVORITE_LOAD_SUCCESS',
    FAVORITE_LOAD_FAIL:'FAVORITE_LOAD_FAIL',
    //收藏模块  --刷新Popular的收藏状态
    FLUSH_POPULAR_FAVORITE:'FLUSH_POPULAR_FAVORITE',
    //收藏模块  --刷新Trending的收藏状态
    TRENDING_FLUSH_FAVORITE:'TRENDING_FLUSH_FAVORITE',
    //最热和趋势上面的tab 显示
    LANGUAGE_LOAD_SUCCESS:'LANGUAGE_LOAD_SUCCESS'


}